spring:
  profiles:
    active: mixed
  datasource:
    url: jdbc:mysql://192.168.123.241:3306/springbatch_sample?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  batch:
    schema: classpath:org/springframework/batch/core/schema-@@platform@@.sql
    initialize-schema: always
    job:
      enabled: false
    table-prefix: BATCH_
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
partition:
  rabbit:
    host: 192.168.123.241
    port: 5672
    username: admin
    password: 123456
    virtualHost: /app/cp
    connRecvThreads: 5
    channelCacheSize: 10



